import { 
  FaLaptop, 
  FaMobileAlt, 
  FaTv, 
  FaTshirt, 
  FaRunning, 
  FaCouch, 
  FaGem, 
  FaHeartbeat,
  FaBookOpen
} from 'react-icons/fa';

export const categories = [
  {
    id: 'electronics',
    name: 'Electronics',
    icon: FaLaptop,
    image: '/products/macbook_air_m2.png',
    path: '/products?category=electronics'
  },
  {
    id: 'fashion',
    name: 'Fashion',
    icon: FaTshirt,
    image: 'https://fakestoreapi.com/img/71-3HjGNDUL._AC_SY879._SX._UX._SY._UY_.jpg',
    path: '/products?category=fashion'
  },
  {
    id: 'gaming',
    name: 'Gaming',
    icon: FaTv,
    image: '/products/playstation_5.png',
    path: '/products?category=gaming'
  },
  {
    id: 'accessories',
    name: 'Accessories',
    icon: FaGem,
    image: 'https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg',
    path: '/products?category=accessories'
  }
];

export const products = [
  {
    name: "Apple iPhone 14 Pro Max (256GB, Silver)",
    description: "Features a stunning 6.7-inch Super Retina XDR display, incredible A16 Bionic chip, and a pro camera system with a 48MP main camera. Perfect for professionals and photography enthusiasts.",
    price: 109900,
    discountPercentage: 10,
    discountPrice: 98910,
    category: "Electronics",
    subcategory: "Phones",
    brand: "Apple",
    image: "/products/iphone_14_pro_max.png",
    stock: 38,
    rating: 4.9,
    numReviews: 1850,
    tag: "best-seller",
    bestSeller: true,
    featured: true,
    newArrival: false,
    trending: true
  },
  {
    name: "Samsung Galaxy S23 Ultra (512GB, Phantom Black)",
    description: "Welcome to the era of ultra-performance. Features a massive 6.8-inch Dynamic AMOLED display, built-in S-Pen, and a revolutionary 200MP quad-telephoto camera system. Designed for creators.",
    price: 124900,
    discountPercentage: 12,
    discountPrice: 109912,
    category: "Electronics",
    subcategory: "Phones",
    brand: "Samsung",
    image: "/products/galaxy_s23_ultra.png",
    stock: 25,
    rating: 4.8,
    numReviews: 760,
    tag: "trending",
    bestSeller: false,
    featured: false,
    newArrival: false,
    trending: true
  },
  {
    name: "Apple MacBook Air M2 (13-inch, 8GB RAM, 256GB SSD)",
    description: "Supercharged by the M2 chip. The incredibly thin and light MacBook Air features a silent, fanless design, up to 18 hours of battery life, and a brilliant Liquid Retina display.",
    price: 99900,
    discountPercentage: 8,
    discountPrice: 91908,
    category: "Electronics",
    subcategory: "Laptops",
    brand: "Apple",
    image: "/products/macbook_air_m2.png",
    stock: 12,
    rating: 4.9,
    numReviews: 2450,
    tag: "featured",
    bestSeller: true,
    featured: true,
    newArrival: false,
    trending: false
  },
  {
    name: "PlayStation 5 Console",
    description: "Experience lightning-fast loading with an ultra-high speed SSD, deeper immersion with support for haptic feedback, adaptive triggers, and 3D Audio, and an incredible new generation of games.",
    price: 49900,
    discountPercentage: 5,
    discountPrice: 47405,
    category: "Gaming",
    subcategory: "Consoles",
    brand: "Sony",
    image: "/products/playstation_5.png",
    stock: 74,
    rating: 4.9,
    numReviews: 5400,
    tag: "best-seller",
    bestSeller: true,
    featured: true,
    newArrival: false,
    trending: true
  },
  {
    name: "Nintendo Switch Console",
    description: "Get the gaming system that lets you play the games you want, wherever you are, however you like. Includes the Nintendo Switch console and Nintendo Switch dock in black.",
    price: 29900,
    discountPercentage: 15,
    discountPrice: 25415,
    category: "Gaming",
    subcategory: "Consoles",
    brand: "Nintendo",
    image: "/products/nintendo_switch.png",
    stock: 150,
    rating: 4.7,
    numReviews: 3200,
    tag: "none",
    bestSeller: false,
    featured: false,
    newArrival: false,
    trending: false
  },
  {
    name: "Sony WH-1000XM4 Wireless Noise Canceling Headphones",
    description: "Industry-leading noise cancellation. Enjoy up to 30 hours of battery life, crystal clear hands-free calling, and exceptional audio quality with dual noise sensor technology.",
    price: 24900,
    discountPercentage: 20,
    discountPrice: 19920,
    category: "Electronics",
    subcategory: "Audio",
    brand: "Sony",
    image: "/products/sony_xm4.png",
    stock: 80,
    rating: 4.8,
    numReviews: 2850,
    tag: "best-seller",
    bestSeller: true,
    featured: true,
    newArrival: false,
    trending: true
  },
  {
    name: "Canon EOS R5 Mirrorless Camera",
    description: "Professional mirrorless camera with a 45MP full-frame CMOS sensor, 8K raw video recording capability, 5-axis in-body image stabilization, and cutting-edge Dual Pixel CMOS AF II.",
    price: 339900,
    discountPercentage: 5,
    discountPrice: 322905,
    category: "Electronics",
    subcategory: "Cameras",
    brand: "Canon",
    image: "/products/canon_eos.png",
    stock: 5,
    rating: 4.8,
    numReviews: 185,
    tag: "featured",
    bestSeller: false,
    featured: true,
    newArrival: false,
    trending: false
  },
  {
    name: "Garmin Fenix 6 Pro Multisport GPS Watch",
    description: "Premium multisport GPS watch featuring mapping, music, intelligent pace planning and more. Battery performance up to 14 days in smartwatch mode and 36 hours in GPS mode.",
    price: 54900,
    discountPercentage: 15,
    discountPrice: 46665,
    category: "Electronics",
    subcategory: "Smart Watches",
    brand: "Garmin",
    image: "/products/garmin_fenix.png",
    stock: 45,
    rating: 4.7,
    numReviews: 420,
    tag: "none",
    bestSeller: false,
    featured: false,
    newArrival: false,
    trending: false
  },
  {
    name: "Xbox Series X Console",
    description: "The fastest, most powerful Xbox ever. Explore rich new worlds with 12 teraflops of raw graphic processing power, DirectX ray tracing, a custom SSD, and 4K gaming.",
    price: 49900,
    discountPercentage: 10,
    discountPrice: 44910,
    category: "Gaming",
    subcategory: "Consoles",
    brand: "Microsoft",
    image: "/products/xbox_series_x.png",
    stock: 35,
    rating: 4.8,
    numReviews: 1250,
    tag: "trending",
    bestSeller: false,
    featured: false,
    newArrival: false,
    trending: true
  },
  {
    name: "Apple AirPods Pro with Wireless Charging Case",
    description: "Active Noise Cancellation for immersive sound. Transparency mode for hearing and connecting with the world around you. Sweat and water-resistant for workouts and runs.",
    price: 24900,
    discountPercentage: 15,
    discountPrice: 21165,
    category: "Electronics",
    subcategory: "Audio",
    brand: "Apple",
    image: "/products/airpods_pro.png",
    stock: 120,
    rating: 4.8,
    numReviews: 4500,
    tag: "best-seller",
    bestSeller: true,
    featured: true,
    newArrival: false,
    trending: false
  },
  {
    name: "Apple Watch Series 7 (Midnight Aluminum, 45mm)",
    description: "The most advanced Apple Watch features blood oxygen monitoring, ECG apps, and a larger Always-On Retina display. Dust resistant and swimproof.",
    price: 42900,
    discountPercentage: 10,
    discountPrice: 38610,
    category: "Electronics",
    subcategory: "Smart Watches",
    brand: "Apple",
    image: "/products/apple_watch_7.png",
    stock: 50,
    rating: 4.9,
    numReviews: 1850,
    tag: "new-arrival",
    bestSeller: false,
    featured: false,
    newArrival: true,
    trending: false
  },
  {
    name: "Fjallraven Foldsack No. 1 Backpack",
    description: "Your perfect pack for everyday use and walks in the town. Made from robust G-1000 HeavyDuty Eco material with a simple folding closure and padded laptop sleeve.",
    price: 8900,
    discountPercentage: 20,
    discountPrice: 7120,
    category: "Fashion",
    subcategory: "Accessories",
    brand: "Fjallraven",
    image: "https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg",
    stock: 65,
    rating: 4.5,
    numReviews: 87,
    tag: "trending",
    bestSeller: false,
    featured: false,
    newArrival: false,
    trending: true
  },
  {
    name: "Men's Casual Premium Slim Fit T-Shirts",
    description: "Slim-fitting style, contrast raglan sleeves, lightweight and soft fabric for breathable, comfortable everyday wear. Available in multiple colors.",
    price: 1800,
    discountPercentage: 15,
    discountPrice: 1530,
    category: "Fashion",
    subcategory: "Men",
    brand: "Generic",
    image: "https://fakestoreapi.com/img/71-3HjGNDUL._AC_SY879._SX._UX._SY._UY_.jpg",
    stock: 150,
    rating: 4.1,
    numReviews: 245,
    tag: "best-seller",
    bestSeller: true,
    featured: false,
    newArrival: false,
    trending: false
  },
  {
    name: "Mens Cotton Utility Jacket",
    description: "Great outerwear jackets for Spring, Autumn, and Winter. Suitable for casual wear, business, outdoor sports, and work. Features multiple utility pockets.",
    price: 4500,
    discountPercentage: 25,
    discountPrice: 3375,
    category: "Fashion",
    subcategory: "Men",
    brand: "Generic",
    image: "https://fakestoreapi.com/img/71li-ujtlVG._AC_UX679_.jpg",
    stock: 38,
    rating: 4.7,
    numReviews: 150,
    tag: "featured",
    bestSeller: false,
    featured: true,
    newArrival: false,
    trending: false
  },
  {
    name: "WD 2TB Elements Portable External Hard Drive",
    description: "USB 3.0 and USB 2.0 Compatibility. Fast data transfers. High capacity in a small enclosure. Plug-and-play ready for Windows PCs.",
    price: 6500,
    discountPercentage: 10,
    discountPrice: 5850,
    category: "Electronics",
    subcategory: "Storage",
    brand: "Western Digital",
    image: "https://fakestoreapi.com/img/61IBBVJvSDL._AC_SY879_.jpg",
    stock: 120,
    rating: 4.8,
    numReviews: 850,
    tag: "none",
    bestSeller: false,
    featured: false,
    newArrival: false,
    trending: false
  },
  {
    name: "SanDisk SSD PLUS 1TB Internal SSD",
    description: "Easy upgrade for faster boot up, shutdown, application load and response. Boosts burst write performance. Ideal for typical PC workloads.",
    price: 8900,
    discountPercentage: 35,
    discountPrice: 5785,
    category: "Electronics",
    subcategory: "Storage",
    brand: "SanDisk",
    image: "https://fakestoreapi.com/img/61U7T1koQqL._AC_SX679_.jpg",
    stock: 85,
    rating: 4.7,
    numReviews: 420,
    tag: "trending",
    bestSeller: false,
    featured: false,
    newArrival: false,
    trending: true
  },
  {
    name: "Acer SB220Q 21.5 inches Full HD IPS Monitor",
    description: "21.5 inches Full HD (1920 x 1080) widescreen IPS display. AMD Radeon FreeSync technology. Zero-frame design with ultra-thin profile.",
    price: 12500,
    discountPercentage: 20,
    discountPrice: 10000,
    category: "Electronics",
    subcategory: "Monitors",
    brand: "Acer",
    image: "https://fakestoreapi.com/img/81QpkIctqPL._AC_SX679_.jpg",
    stock: 30,
    rating: 4.5,
    numReviews: 245,
    tag: "featured",
    bestSeller: false,
    featured: true,
    newArrival: false,
    trending: false
  },
  {
    name: "Samsung 49-Inch CHG90 144Hz Curved Gaming Monitor",
    description: "Super ultra-wide 49 inch curved gaming monitor. Quantum dot (QLED) technology. HDR support and 144Hz refresh rate for incredibly smooth gameplay.",
    price: 85000,
    discountPercentage: 15,
    discountPrice: 72250,
    category: "Electronics",
    subcategory: "Monitors",
    brand: "Samsung",
    image: "https://fakestoreapi.com/img/81Zt42O02K._AC_SX679_.jpg",
    stock: 10,
    rating: 4.6,
    numReviews: 180,
    tag: "new-arrival",
    bestSeller: false,
    featured: false,
    newArrival: true,
    trending: false
  },
  {
    name: "BIYLACLESEN Women's 3-in-1 Snowboard Winter Coat",
    description: "Warm fleece lining with a waterproof and windproof exterior. Adjustable cuffs and detachable hood. Perfect for skiing, snowboarding, and harsh winters.",
    price: 7500,
    discountPercentage: 40,
    discountPrice: 4500,
    category: "Fashion",
    subcategory: "Women",
    brand: "BIYLACLESEN",
    image: "https://fakestoreapi.com/img/51Y5NI-I5jL._AC_UX679_.jpg",
    stock: 45,
    rating: 4.3,
    numReviews: 87,
    tag: "trending",
    bestSeller: false,
    featured: false,
    newArrival: false,
    trending: true
  },
  {
    name: "John Hardy Women's Naga Gold & Silver Dragon Bracelet",
    description: "From our Legends Collection, the Naga was inspired by the mythical water dragon that protects the ocean's pearl. Beautiful handcrafted 18K gold and silver.",
    price: 45000,
    discountPercentage: 5,
    discountPrice: 42750,
    category: "Accessories",
    subcategory: "Jewelry",
    brand: "John Hardy",
    image: "https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg",
    stock: 5,
    rating: 4.8,
    numReviews: 15,
    tag: "featured",
    bestSeller: false,
    featured: true,
    newArrival: false,
    trending: false
  }
];
